---
repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
        files: ^(components/.+)?[^/]+\.py$
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings==1.5.0
          - pydocstyle==5.1.1
        files: ^(components)/.+\.py$
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
