sunpower_solar:
  arrays:
    - id: array_${array}
      name: Array ${array}

sensor:
  - platform: sunpower_solar
    arrays:
      array_${array}:
        current: ${node_friendly_name} Array ${array} Current
        power: ${node_friendly_name} Array ${array} Active Power
        lifetime_energy: ${node_friendly_name} Array ${array} Lifetime Energy
